using InnManager.Billing;
using InnManager.Employees;
using InnManager.Enums;
using InnManager.Guests;
using InnManager.Housekeeping;
using InnManager.Reservations;
using InnManager.Rooms;
using InnManager.Services;
using System;
using System.Collections.Generic;
using System.Text;

namespace InnManager.Hotels
{
    /// <summary>
    /// Represents a hotel in the inn management system.
    /// </summary>
    public class Hotel
    {
        #region Properties
        /// <summary>
        /// Gets or sets the name of the hotel.
        /// </summary>
        public string Name { get; init; }
        /// <summary>
        /// Gets or sets the type of the hotel, represented by the HotelType enum. This property allows for categorization of hotels into predefined types such as Boutique, Resort, Business, etc.
        /// </summary>
        public HotelType Type { get; init; }
        /// <summary>
        /// Gets the list of rooms in the hotel.
        /// </summary>
        public List<Room> Rooms { get; } = new List<Room>();
        /// <summary>
        /// Gets the list of guests in the hotel.
        /// </summary>
        public List<Guest> Guests { get; } = new List<Guest>();
        /// <summary>
        /// Gets the list of reservations in the hotel. 
        /// </summary>
        public List<Reservation> Reservations { get; } = new List<Reservation>();
        /// <summary>
        /// Gets the list of services offered by the hotel.
        /// </summary>
        public List<Service> Services { get; } = new List<Service>();
        /// <summary>
        /// Gets the list of invoices generated by the hotel.
        /// </summary>
        public List<Invoice> Invoices { get; } = new List<Invoice>();
        /// <summary>
        /// Gets the list of payments made by guests in the hotel.
        /// </summary>
        public List<Payment> Payments { get; } = new List<Payment>();
        /// <summary>
        /// Gets the list of employees working in the hotel.
        /// </summary>
        public List<Employee> Employees { get; } = new List<Employee>();
        /// <summary>
        /// Gets the list of housekeeping tasks assigned to the hotel.
        /// </summary>
        public List<HousekeepingTask> HousekeepingTasks { get; } = new List<HousekeepingTask>();
        /// <summary>
        /// Gets the count of available rooms in the hotel.
        /// </summary>
        public int AvailableRoomCount => Rooms.Count(r => r.isAvailable);
        /// <summary>
        /// Gets the count of occupied rooms in the hotel.
        /// </summary>
        public int OccupiedRoomCount => Rooms.Count(r => !r.isAvailable);

        #endregion
        /// <summary>
        /// Initializes a new instance of the Hotel class with the specified name and type.
        /// </summary>
        /// <param name="name"></param>
        /// <param name="type"></param>
        public Hotel(string name, HotelType type)
        {
            Name = name;
            Type = type;
        }
    }
}
